// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Software_2.Data;

#nullable disable

namespace Software_2.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Software_2.Models.Auditorium", b =>
                {
                    b.Property<int>("IdAuditoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_auditoria");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAuditoria"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Detalles")
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaAccion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("Fecha_accion")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("IdRegistroAfectado")
                        .HasColumnType("int")
                        .HasColumnName("ID_registro_afectado");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("ID_usuario");

                    b.Property<string>("TablaAfectada")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Tabla_afectada");

                    b.HasKey("IdAuditoria")
                        .HasName("PK__Auditori__F6FFFB8CDB49D4A3");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Auditoria");
                });

            modelBuilder.Entity("Software_2.Models.CategoriaDonacion", b =>
                {
                    b.Property<int>("IdCategoriaDonacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_categoria_donacion");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCategoriaDonacion"));

                    b.Property<bool?>("Activa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Descripción")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("NombreCategoria")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Nombre_categoria");

                    b.HasKey("IdCategoriaDonacion")
                        .HasName("PK__Categori__A114E90C7B3A1776");

                    b.ToTable("Categoria_Donacion", (string)null);
                });

            modelBuilder.Entity("Software_2.Models.ComentariosValoracione", b =>
                {
                    b.Property<int>("IdComentario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_comentario");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdComentario"));

                    b.Property<bool?>("Aprobado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Comentario")
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaComentario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("Fecha_comentario")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("IdDonacion")
                        .HasColumnType("int")
                        .HasColumnName("ID_donacion");

                    b.Property<int>("IdFundacion")
                        .HasColumnType("int")
                        .HasColumnName("ID_fundacion");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("ID_usuario");

                    b.Property<bool?>("Reportado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Respuesta")
                        .HasColumnType("text");

                    b.Property<int?>("Valoracion")
                        .HasColumnType("int");

                    b.HasKey("IdComentario")
                        .HasName("PK__Comentar__4DF668A631E18AE2");

                    b.HasIndex("IdDonacion");

                    b.HasIndex("IdFundacion");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Comentarios_Valoraciones", (string)null);
                });

            modelBuilder.Entity("Software_2.Models.Configuracione", b =>
                {
                    b.Property<int>("IdConfiguracion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_configuracion");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdConfiguracion"));

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Descripción")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("IdConfiguracion")
                        .HasName("PK__Configur__90679C80EF052937");

                    b.ToTable("Configuraciones");
                });

            modelBuilder.Entity("Software_2.Models.Documento", b =>
                {
                    b.Property<int>("IdDocumento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_documento");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDocumento"));

                    b.Property<string>("RutaDoc")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Ruta_doc");

                    b.Property<string>("TipoDocumento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Tipo_documento");

                    b.HasKey("IdDocumento")
                        .HasName("PK__Document__B6ED5B3ED2F4B3DB");

                    b.ToTable("Documento", (string)null);
                });

            modelBuilder.Entity("Software_2.Models.Donacione", b =>
                {
                    b.Property<int>("IdDonacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_donacion");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDonacion"));

                    b.Property<int?>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("DescripciónDonacion")
                        .HasColumnType("text")
                        .HasColumnName("Descripción_donacion");

                    b.Property<DateTime>("FechaDonacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("Fecha_donacion")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("IdCategoriaDonacion")
                        .HasColumnType("int")
                        .HasColumnName("ID_categoria_donacion");

                    b.Property<int>("IdEstado")
                        .HasColumnType("int")
                        .HasColumnName("ID_estado");

                    b.Property<int>("IdFundacion")
                        .HasColumnType("int")
                        .HasColumnName("ID_fundacion");

                    b.Property<int?>("IdPublicacion")
                        .HasColumnType("int")
                        .HasColumnName("ID_publicacion");

                    b.Property<int>("IdUsuarioDonante")
                        .HasColumnType("int")
                        .HasColumnName("ID_usuario_donante");

                    b.Property<string>("Ubicacion")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("IdDonacion")
                        .HasName("PK__Donacion__D588707BC603EBC8");

                    b.HasIndex("IdCategoriaDonacion");

                    b.HasIndex("IdEstado");

                    b.HasIndex("IdFundacion");

                    b.HasIndex("IdPublicacion");

                    b.HasIndex("IdUsuarioDonante");

                    b.ToTable("Donaciones");
                });

            modelBuilder.Entity("Software_2.Models.Estado", b =>
                {
                    b.Property<int>("IdEstado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_estado");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEstado"));

                    b.Property<string>("NombreEstado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Nombre_estado");

                    b.HasKey("IdEstado")
                        .HasName("PK__Estado__BDA876FE0E42CB61");

                    b.ToTable("Estado", (string)null);
                });

            modelBuilder.Entity("Software_2.Models.FundacionDocumento", b =>
                {
                    b.Property<int>("IdFundacionDocumento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_fundacion_documento");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFundacionDocumento"));

                    b.Property<int>("IdDocumento")
                        .HasColumnType("int")
                        .HasColumnName("ID_documento");

                    b.Property<int>("IdFundacion")
                        .HasColumnType("int")
                        .HasColumnName("ID_fundacion");

                    b.HasKey("IdFundacionDocumento")
                        .HasName("PK__Fundacio__231018117EC74A1D");

                    b.HasIndex("IdDocumento");

                    b.HasIndex("IdFundacion");

                    b.ToTable("Fundacion_Documento", (string)null);
                });

            modelBuilder.Entity("Software_2.Models.Fundación", b =>
                {
                    b.Property<int>("IdFundacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_fundacion");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFundacion"));

                    b.Property<bool?>("Activa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Descripción")
                        .HasColumnType("text");

                    b.Property<string>("Dirección")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("Fecha_registro")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("IdTipoActividad")
                        .HasColumnType("int")
                        .HasColumnName("ID_tipo_actividad");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("ID_usuario");

                    b.Property<string>("Nif")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("NIF");

                    b.Property<string>("NombreLegal")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("Nombre_legal");

                    b.Property<string>("SitioWeb")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Sitio_web");

                    b.HasKey("IdFundacion")
                        .HasName("PK__Fundació__DC9FE4B8AEB06F64");

                    b.HasIndex("IdTipoActividad");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Fundación", (string)null);
                });

            modelBuilder.Entity("Software_2.Models.Notificacione", b =>
                {
                    b.Property<int>("IdNotificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_notificacion");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdNotificacion"));

                    b.Property<bool?>("Enviada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("FechaEnvio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("Fecha_envio")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("IdDonacion")
                        .HasColumnType("int")
                        .HasColumnName("ID_donacion");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("ID_usuario");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TipoNotificacion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Tipo_notificacion");

                    b.HasKey("IdNotificacion")
                        .HasName("PK__Notifica__99BC7E5E05435B87");

                    b.HasIndex("IdDonacion");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Notificaciones");
                });

            modelBuilder.Entity("Software_2.Models.Publicacione", b =>
                {
                    b.Property<int>("IdPublicacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_publicacion");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPublicacion"));

                    b.Property<bool?>("Activa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Descripción")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime")
                        .HasColumnName("Fecha_fin");

                    b.Property<DateTime>("FechaInicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("Fecha_inicio")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("IdCategoriaDonacion")
                        .HasColumnType("int")
                        .HasColumnName("ID_categoria_donacion");

                    b.Property<int>("IdFundacion")
                        .HasColumnType("int")
                        .HasColumnName("ID_fundacion");

                    b.Property<int?>("MetaCantidad")
                        .HasColumnType("int")
                        .HasColumnName("Meta_cantidad");

                    b.Property<string>("NombrePublicacion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("Nombre_publicacion");

                    b.HasKey("IdPublicacion")
                        .HasName("PK__Publicac__1E838F30552D3200");

                    b.HasIndex("IdCategoriaDonacion");

                    b.HasIndex("IdFundacion");

                    b.ToTable("Publicaciones");
                });

            modelBuilder.Entity("Software_2.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("datetime");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("IdUsuario");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Software_2.Models.Role", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_rol");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRol"));

                    b.Property<string>("NombreRol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Nombre_rol");

                    b.HasKey("IdRol")
                        .HasName("PK__Roles__182A541257759658");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Software_2.Models.TipoActividad", b =>
                {
                    b.Property<int>("IdTipoActividad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_tipo_actividad");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoActividad"));

                    b.Property<string>("NombreTipoActividad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Nombre_tipo_actividad");

                    b.HasKey("IdTipoActividad")
                        .HasName("PK__Tipo_Act__A0909E146C0D0245");

                    b.ToTable("Tipo_Actividad", (string)null);
                });

            modelBuilder.Entity("Software_2.Models.TipoDocumento", b =>
                {
                    b.Property<int>("IdTipoDocumento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_tipo_documento");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoDocumento"));

                    b.Property<string>("NombreTipoDocumento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Nombre_tipo_documento");

                    b.HasKey("IdTipoDocumento")
                        .HasName("PK__Tipo_Doc__FEB84E2351A2976D");

                    b.ToTable("Tipo_Documento", (string)null);
                });

            modelBuilder.Entity("Software_2.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_usuario");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<bool?>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("ApellidoUsuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Apellido_usuario");

                    b.Property<string>("ContraseñaUsuario")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Contraseña_usuario");

                    b.Property<string>("CorreoUsuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Correo_usuario");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("Fecha_registro")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("IdRol")
                        .HasColumnType("int")
                        .HasColumnName("ID_rol");

                    b.Property<int>("IdTipoDocumento")
                        .HasColumnType("int")
                        .HasColumnName("ID_tipo_documento");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Nombre_usuario");

                    b.Property<string>("NumeroDocumento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Numero_documento");

                    b.Property<string>("TelUsuario")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Tel_usuario");

                    b.Property<DateTime?>("UltimoAcceso")
                        .HasColumnType("datetime")
                        .HasColumnName("Ultimo_acceso");

                    b.HasKey("IdUsuario")
                        .HasName("PK__Usuarios__DF3D4252DE2473BB");

                    b.HasIndex("IdRol");

                    b.HasIndex("IdTipoDocumento");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("Software_2.Models.Auditorium", b =>
                {
                    b.HasOne("Software_2.Models.Usuario", "IdUsuarioNavigation")
                        .WithMany("Auditoria")
                        .HasForeignKey("IdUsuario")
                        .IsRequired()
                        .HasConstraintName("FK_Auditoria_Usuarios");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("Software_2.Models.ComentariosValoracione", b =>
                {
                    b.HasOne("Software_2.Models.Donacione", "IdDonacionNavigation")
                        .WithMany("ComentariosValoraciones")
                        .HasForeignKey("IdDonacion")
                        .HasConstraintName("FK_Comentarios_Valoraciones_Donaciones");

                    b.HasOne("Software_2.Models.Fundación", "IdFundacionNavigation")
                        .WithMany("ComentariosValoraciones")
                        .HasForeignKey("IdFundacion")
                        .IsRequired()
                        .HasConstraintName("FK_Comentarios_Valoraciones_Fundación");

                    b.HasOne("Software_2.Models.Usuario", "IdUsuarioNavigation")
                        .WithMany("ComentariosValoraciones")
                        .HasForeignKey("IdUsuario")
                        .IsRequired()
                        .HasConstraintName("FK_Comentarios_Valoraciones_Usuarios");

                    b.Navigation("IdDonacionNavigation");

                    b.Navigation("IdFundacionNavigation");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("Software_2.Models.Donacione", b =>
                {
                    b.HasOne("Software_2.Models.CategoriaDonacion", "IdCategoriaDonacionNavigation")
                        .WithMany("Donaciones")
                        .HasForeignKey("IdCategoriaDonacion")
                        .IsRequired()
                        .HasConstraintName("FK_Donaciones_Categoria_Donacion");

                    b.HasOne("Software_2.Models.Estado", "IdEstadoNavigation")
                        .WithMany("Donaciones")
                        .HasForeignKey("IdEstado")
                        .IsRequired()
                        .HasConstraintName("FK_Donaciones_Estado");

                    b.HasOne("Software_2.Models.Fundación", "IdFundacionNavigation")
                        .WithMany("Donaciones")
                        .HasForeignKey("IdFundacion")
                        .IsRequired()
                        .HasConstraintName("FK_Donaciones_Fundación");

                    b.HasOne("Software_2.Models.Publicacione", "IdPublicacionNavigation")
                        .WithMany("Donaciones")
                        .HasForeignKey("IdPublicacion")
                        .HasConstraintName("FK_Donaciones_Publicaciones");

                    b.HasOne("Software_2.Models.Usuario", "IdUsuarioDonanteNavigation")
                        .WithMany("Donaciones")
                        .HasForeignKey("IdUsuarioDonante")
                        .IsRequired()
                        .HasConstraintName("FK_Donaciones_Usuarios");

                    b.Navigation("IdCategoriaDonacionNavigation");

                    b.Navigation("IdEstadoNavigation");

                    b.Navigation("IdFundacionNavigation");

                    b.Navigation("IdPublicacionNavigation");

                    b.Navigation("IdUsuarioDonanteNavigation");
                });

            modelBuilder.Entity("Software_2.Models.FundacionDocumento", b =>
                {
                    b.HasOne("Software_2.Models.Documento", "IdDocumentoNavigation")
                        .WithMany("FundacionDocumentos")
                        .HasForeignKey("IdDocumento")
                        .IsRequired()
                        .HasConstraintName("FK_Fundacion_Documento_Documento");

                    b.HasOne("Software_2.Models.Fundación", "IdFundacionNavigation")
                        .WithMany("FundacionDocumentos")
                        .HasForeignKey("IdFundacion")
                        .IsRequired()
                        .HasConstraintName("FK_Fundacion_Documento_Fundación");

                    b.Navigation("IdDocumentoNavigation");

                    b.Navigation("IdFundacionNavigation");
                });

            modelBuilder.Entity("Software_2.Models.Fundación", b =>
                {
                    b.HasOne("Software_2.Models.TipoActividad", "IdTipoActividadNavigation")
                        .WithMany("Fundacións")
                        .HasForeignKey("IdTipoActividad")
                        .IsRequired()
                        .HasConstraintName("FK_Fundación_Tipo_Actividad");

                    b.HasOne("Software_2.Models.Usuario", "IdUsuarioNavigation")
                        .WithMany("Fundacións")
                        .HasForeignKey("IdUsuario")
                        .IsRequired()
                        .HasConstraintName("FK_Fundación_Usuarios");

                    b.Navigation("IdTipoActividadNavigation");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("Software_2.Models.Notificacione", b =>
                {
                    b.HasOne("Software_2.Models.Donacione", "IdDonacionNavigation")
                        .WithMany("Notificaciones")
                        .HasForeignKey("IdDonacion")
                        .HasConstraintName("FK_Notificaciones_Donaciones");

                    b.HasOne("Software_2.Models.Usuario", "IdUsuarioNavigation")
                        .WithMany("Notificaciones")
                        .HasForeignKey("IdUsuario")
                        .IsRequired()
                        .HasConstraintName("FK_Notificaciones_Usuarios");

                    b.Navigation("IdDonacionNavigation");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("Software_2.Models.Publicacione", b =>
                {
                    b.HasOne("Software_2.Models.CategoriaDonacion", "IdCategoriaDonacionNavigation")
                        .WithMany("Publicaciones")
                        .HasForeignKey("IdCategoriaDonacion")
                        .HasConstraintName("FK_Publicaciones_Categoria_Donacion");

                    b.HasOne("Software_2.Models.Fundación", "IdFundacionNavigation")
                        .WithMany("Publicaciones")
                        .HasForeignKey("IdFundacion")
                        .IsRequired()
                        .HasConstraintName("FK_Publicaciones_Fundación");

                    b.Navigation("IdCategoriaDonacionNavigation");

                    b.Navigation("IdFundacionNavigation");
                });

            modelBuilder.Entity("Software_2.Models.RefreshToken", b =>
                {
                    b.HasOne("Software_2.Models.Usuario", "Usuario")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Software_2.Models.Usuario", b =>
                {
                    b.HasOne("Software_2.Models.Role", "IdRolNavigation")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.ClientNoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Usuarios_Roles");

                    b.HasOne("Software_2.Models.TipoDocumento", "IdTipoDocumentoNavigation")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdTipoDocumento")
                        .OnDelete(DeleteBehavior.ClientNoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Usuarios_Tipo_Documento");

                    b.Navigation("IdRolNavigation");

                    b.Navigation("IdTipoDocumentoNavigation");
                });

            modelBuilder.Entity("Software_2.Models.CategoriaDonacion", b =>
                {
                    b.Navigation("Donaciones");

                    b.Navigation("Publicaciones");
                });

            modelBuilder.Entity("Software_2.Models.Documento", b =>
                {
                    b.Navigation("FundacionDocumentos");
                });

            modelBuilder.Entity("Software_2.Models.Donacione", b =>
                {
                    b.Navigation("ComentariosValoraciones");

                    b.Navigation("Notificaciones");
                });

            modelBuilder.Entity("Software_2.Models.Estado", b =>
                {
                    b.Navigation("Donaciones");
                });

            modelBuilder.Entity("Software_2.Models.Fundación", b =>
                {
                    b.Navigation("ComentariosValoraciones");

                    b.Navigation("Donaciones");

                    b.Navigation("FundacionDocumentos");

                    b.Navigation("Publicaciones");
                });

            modelBuilder.Entity("Software_2.Models.Publicacione", b =>
                {
                    b.Navigation("Donaciones");
                });

            modelBuilder.Entity("Software_2.Models.Role", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Software_2.Models.TipoActividad", b =>
                {
                    b.Navigation("Fundacións");
                });

            modelBuilder.Entity("Software_2.Models.TipoDocumento", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Software_2.Models.Usuario", b =>
                {
                    b.Navigation("Auditoria");

                    b.Navigation("ComentariosValoraciones");

                    b.Navigation("Donaciones");

                    b.Navigation("Fundacións");

                    b.Navigation("Notificaciones");

                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
